name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on every branch push

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Set up JDK 11  # Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Jenkinsfile Runner
        run: |
            curl -L -o jenkinsfile-runner.tar.gz https://github.com/jenkinsci/jenkinsfile-runner/releases/download/1.0-beta-28/jenkinsfile-runner.tar.gz
            mkdir jenkinsfile-runner
            tar -xzf jenkinsfile-runner.tar.gz -C jenkinsfile-runner




      - name: Run Jenkinsfile
        run: |
          ./jenkinsfile-runner/bin/jenkinsfile-runner -w ./jenkinsfile-runner -p ./jenkinsfile-runner/plugins -f Jenkinsfile
