name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on all branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Run Jenkinsfile Runner in Docker with Java 17
        run: |
          docker run --rm \
            -v $(pwd):/workspace -w /workspace \
            jenkins/jenkinsfile-runner:jdk17 \
            --file /workspace/Jenkinsfile


