name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on all branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

    
      - name: Checkout Code
        uses: actions/checkout@v3  
      - name: Run Jenkinsfile Runner with Java 17 in Docker
        run: |
          docker run --rm \
            -e JAVA_HOME=/opt/java/openjdk \
            -e PATH="/opt/java/openjdk/bin:$PATH" \
            -v $(pwd):/workspace -w /workspace \
            ghcr.io/jenkinsci/jenkinsfile-runner:master


