name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on all branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

    
      - name: Checkout Code
        uses: actions/checkout@v3  
      - name: Install Node.js and npm
        run: |
          sudo apt update
          sudo apt install -y nodejs npm

      - name: Run Jenkinsfile Runner with Node.js & Java (Fixed npm Permissions)
        run: |
          docker run --rm \
            -e JAVA_HOME=/opt/java/openjdk \
            -e PATH="/opt/java/openjdk/bin:$PATH:/usr/bin" \
            -v $(pwd):/workspace -w /workspace \
            cimg/node:18.16-browsers bash -c "
            mkdir -p ~/.npm-global && \
            npm config set prefix '~/.npm-global' && \
            export PATH=~/.npm-global/bin:$PATH && \
            npm install yarn && \
            npx yarn install && \
            ghcr.io/jenkinsci/jenkinsfile-runner:master"

