name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on all branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Set up Node.js and Install Yarn
        run: |
          docker run --rm \
            -v $(pwd):/workspace -w /workspace \
            node:18-bullseye bash -c "
            apt update && apt install -y curl && \
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
            apt install -y nodejs && \
            npm install -g yarn && \
            yarn install"

      - name: Run Jenkinsfile Runner
        run: |
          docker run --rm \
            -e JAVA_HOME=/opt/java/openjdk \
            -e PATH="/opt/java/openjdk/bin:$PATH:/usr/bin" \
            -v $(pwd):/workspace -w /workspace \
            ghcr.io/jenkinsci/jenkinsfile-runner:master run \
            --file /workspace/Jenkinsfile
