name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on every branch push

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Set up JDK 11  # Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Jenkinsfile Runner using GitHub Packages
        run: |
          mkdir jenkinsfile-runner
          wget https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/1.0-beta-29/jenkinsfile-runner-1.0-beta-29.zip
          unzip jenkinsfile-runner-1.0-beta-29.zip -d jenkinsfile-runner


      - name: Run Jenkinsfile
        run: |
          ./jenkinsfile-runner/bin/jenkinsfile-runner -w ./jenkinsfile-runner -p ./jenkinsfile-runner/plugins -f Jenkinsfile
