name: Jenkinsfile Runner CI  # Name of the workflow

on:
  push:
    branches:
      - '*'  # Runs on every branch push

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Code  # Step 1: Fetch the latest code
        uses: actions/checkout@v3  

      - name: Set up JDK 11  # Step 2: Install Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Jenkinsfile Runner  # Step 3: Install Jenkinsfile Runner
        run: |
          curl -L -o jenkinsfile-runner.tar.gz https://github.com/jenkinsci/jenkinsfile-runner/releases/latest/download/jenkinsfile-runner.tar.gz
          mkdir jenkinsfile-runner
          tar -xzf jenkinsfile-runner.tar.gz -C jenkinsfile-runner

      - name: Run Jenkinsfile  # Step 4: Run the Jenkins pipeline
        run: |
          ./jenkinsfile-runner/bin/jenkinsfile-runner -w ./jenkinsfile-runner -p ./jenkinsfile-runner/plugins -f Jenkinsfile
