name: Jenkinsfile Runner CI

on:
  push:
    branches:
      - '*'  # Runs on all branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'  # Caches dependencies

      - name: Install Yarn Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run Jenkinsfile Runner in Docker
        run: |
          docker run --rm \
            -e JAVA_HOME=/opt/java/openjdk \
            -v $(pwd):/workspace -w /workspace \
            ghcr.io/jenkinsci/jenkinsfile-runner:master run \
            --file /workspace/Jenkinsfile
